after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

service_name: travis-pro
repo_token: U74tX7oVwlfPhtSp7jORqQn7np7JVtsnL
